services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  api:
    build:
      context: ./back-efra
      dockerfile: dockerfile
    command: npm run dev
    volumes:
      - ./back-efra:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./back-efra/.env
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
    depends_on:
      - db

  # Servicio del Frontend (React/Vite)
  frontend:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./landing:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - api

volumes:
  postgres_data:
